name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: node:10
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: abhinavdevops01
          password: Abhinav_cool1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: abhinavdevops01/myappv1:${{github.sha}}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
